services:
  rust_dev:
    build:
      context: .
      target: dev
    volumes:
      - .:/usr/src/myapp
    environment:
      - USER=fdbiondi
      - PORT=8080
    ports:
      - 8080:8080
    networks:
      - rust-net

networks:
  rust-net:
    driver: bridge
